version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/postgres:9.5.18-alpine
        environment:
          DB_HOST: 127.0.0.1
    steps:
      - checkout
      - restore_cache:
          name: Restore bundle cache
          keys:
            - v1-rp-bundle-{{ checksum "Gemfile.lock" }}-{{ arch }}
            - v1-rp-bundle-
      - run:
          name: Bundle install
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs 4 --retry 3
      - save_cache:
          name: Store bundle cache
          key: v1-rp-bundle-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - run:
          name: Setup DB
          command: |
            bundle exec rails db:create db:migrate
      - run:
          name: RSpec
          when: always
          command: |
            bundle exec rspec
